spring:
  cache:
    type:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: qweR
  jpa:
    hibernate:
      ddl-auto: none
#    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
#  sql:
#    init:
#      mode: always